### ISSUE TITLE
Worker fails with exception if none of the new exposed environment variables are set

### ISSUE THREAD

**Issue by Klaus-Nji-sp** [zeebe-io/zeebe-http-worker#28]
Checked out the most recent changes and attempted to run the worker without setting any of the new environmental variables such as ENV_VARS_URL (e.g. http://someUrl/config, default: null)
ENV_VARS_RELOAD_RATE (defaullt 15000), etc.

When worker is invoked, the following exception is raised:

```
java.lang.RuntimeException: Could not load variables from 'null': URI with undefined scheme
	at io.zeebe.http.EnvironmentVariableProvider.getVariables(EnvironmentVariableProvider.java:91) ~[classes/:na]
	at io.zeebe.http.HttpJobHandler.handle(HttpJobHandler.java:57) ~[classes/:na]
	at io.zeebe.http.ZeebeHttpWorkerApplication.handleFooJob(ZeebeHttpWorkerApplication.java:62) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at io.zeebe.spring.client.bean.MethodInfo.invoke(MethodInfo.java:31) ~[spring-zeebe-0.7.1.jar:0.7.1]
	at io.zeebe.spring.client.config.processor.ZeebeWorkerPostProcessor.lambda$null$1(ZeebeWorkerPostProcessor.java:49) ~[spring-zeebe-0.7.1.jar:0.7.1]
	at io.zeebe.client.impl.worker.JobRunnableFactory.executeJob(JobRunnableFactory.java:44) ~[zeebe-client-java-0.21.1.jar:0.21.1]
	at io.zeebe.client.impl.worker.JobRunnableFactory.lambda$create$0(JobRunnableFactory.java:39) ~[zeebe-client-java-0.21.1.jar:0.21.1]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.lang.IllegalArgumentException: URI with undefined scheme
	at java.net.http/jdk.internal.net.http.common.Utils.newIAE(Utils.java:244) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.HttpRequestBuilderImpl.checkURI(HttpRequestBuilderImpl.java:79) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.HttpRequestBuilderImpl.uri(HttpRequestBuilderImpl.java:71) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.HttpRequestBuilderImpl.uri(HttpRequestBuilderImpl.java:43) ~[java.net.http:na]
	at io.zeebe.http.EnvironmentVariableProvider.refreshM2mToken(EnvironmentVariableProvider.java:132) ~[classes/:na]
	at io.zeebe.http.EnvironmentVariableProvider.createHttpRequest(EnvironmentVariableProvider.java:102) ~[classes/:na]
	at io.zeebe.http.EnvironmentVariableProvider.getVariables(EnvironmentVariableProvider.java:65) ~[classes/:na]
```

I am also able to duplicate the problem by commenting out these lines in the unit test:

```
@SpringBootTest(properties = {
    "ENV_VARS_URL=http://localhost:8089/config", "ENV_VARS_RELOAD_RATE=0",    
    "ENV_VARS_M2M_BASE_URL:http://localhost:8089/token", "ENV_VARS_M2M_CLIENT_ID:someClientId", "ENV_VARS_M2M_CLIENT_SECRET:someSecret", "ENV_VARS_M2M_AUDIENCE:someAudience"})
```

If these are optional configuration parameters, the worker should not fail.  

The purpose of these new environment variables is also not quite clear.

**Comment by berndruecker** [comment]
Thanks @Klaus-Nji-sp for reporting! Fixed

**Comment by Klaus-Nji-sp** [comment]
@berndruecker, thanks for the fix.  I do realize this PR is closed and will open a new issue if this is really an issue but here is a new behavior I have found with the new release.

I now have to create an output mapping with source defined as statusCode and target defined as statusCode to be able to use the value of statusCode returned from the http task in an exclusive gateway.  Did not have to do this before.  Is this desired behavior?

**Comment by berndruecker** [comment]
Hey @Klaus-Nji-sp: This is wired - it should actually be totally standard behavior: https://github.com/zeebe-io/zeebe-http-worker/blob/master/src/main/java/io/zeebe/http/HttpJobHandler.java#L69

**Comment by Klaus-Nji-sp** [comment]
Yes, it is weird.  I'll keep investigating.  In the meantime, I am ok with the mapping.... but perhaps this behavior should be well understood.

**Comment by berndruecker** [comment]
Yeah! Would be awesome if you could investigate a bit more. And also feel free to open an issue for it
