### ISSUE TITLE
default for ENV_VARS_RELOAD_RATE not working

### ISSUE THREAD

**Issue by ultraschuppi** [zeebe-io/zeebe-http-worker#29]
we are trying to get the zeebe-http-worker into camunda-cloud, these are the env-vars we are setting for the container:

```
**    Environment:
      DEBUG:                             express:*
      ZEEBE_CLIENT_BROKER_CONTACTPOINT:  zeebe-service
      CLUSTER_NAME:                      XXX
      ENV_VARS_URL:                      https://variables.XXX/private/variables/XXX
      ENV_VARS_M2M_BASE_URL:             https://login.cloud.XXX/oauth/token
      ENV_VARS_M2M_CLIENT_ID:            XXX
      ENV_VARS_M2M_CLIENT_SECRET:        XXX
      ENV_VARS_M2M_AUDIENCE:             variables.XXX
**
```

```
10:57:25.975 [main] WARN org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'zeebeHttpWorkerApplication': Unsatisfied dependency expressed through field 'jobHandler'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'httpJobHandler': Unsatisfied dependency expressed through field 'environmentVariableProvider'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'environmentVariableProvider': Unsatisfied dependency expressed through field 'config'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'zeebeHttpWorkerConfig': Unsatisfied dependency expressed through field 'environmentVariablesReloadIntervalMs'; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'long'; nested exception is java.lang.NumberFormatException: For input string: "${ENV_VARS_RELOAD_RATE:15000}"
10:57:26.074 [main] WARN org.springframework.beans.factory.support.DisposableBeanAdapter - Destroy method 'close' on bean with name 'zeebeClientLifecycle' threw an exception
java.lang.NullPointerException: null
	at io.zeebe.spring.util.ZeebeAutoStartUpLifecycle.stop(ZeebeAutoStartUpLifecycle.java:62)
	at io.zeebe.spring.util.ZeebeAutoStartUpLifecycle.stop(ZeebeAutoStartUpLifecycle.java:71)
	at io.zeebe.spring.client.ZeebeClientLifecycle.close(ZeebeClientLifecycle.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:339)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:273)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:571)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:543)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1072)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:504)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1065)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1060)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:563)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at io.zeebe.http.ZeebeHttpWorkerApplication.main(ZeebeHttpWorkerApplication.java:39)
10:57:26.371 [main] ERROR org.springframework.boot.SpringApplication - Application run failed

```

we aren't setting `ENV_VARS_RELOAD_RATE` intentionally and were expecting the default would kick in ;-)

**Comment by ultraschuppi** [comment]
probably relates-to/same-as #28

**Comment by afirth** [comment]
my guess is that `"${ENV_VARS_RELOAD_RATE:15000}"` returns a string, which would need to be cast to `long` by the getter
should this be `=` instead at https://github.com/zeebe-io/zeebe-http-worker/blob/7c670dc7cd45553dc7396f2b50af1a08a039f52a/src/main/java/io/zeebe/http/ZeebeHttpWorkerConfig.java#L16 - like https://github.com/zeebe-io/zeebe-http-worker/blob/7abec1919f4754e0239f616ba59258987a422167/src/test/java/io/zeebe/http/WorkflowTest.java#L33 ? or is this javaspeak for default condition like shell?

**Comment by berndruecker** [comment]
This was actually a problem in the build itself, not adding all necessary Spring dependencies leading to properties not being resolved. Should be fixed now
