### ISSUE TITLE
Running Docker image fails

### ISSUE THREAD

**Issue by manideep418** [zeebe-io/zeebe-http-worker#44]
Running the docker image using docker-compose file fails. docker run not reading the environment variables specified in the docker-compose file.
`version: "2"

services:  
  zeebe:
    container_name: zeebe_worker_lock_order
    image: camunda/zeebe-http-worker
    environment:
      - ZEEBE_CLIENT_WORKER_DEFAULTNAME='Lock Order'
      - ZEEBE_CLIENT_WORKER_DEFAULTTYPE='LockOrder'
      - ZEEBE_CLIENT_BROKER_CONTACTPOINT='zeebe-dev.cl.local:443'

    

`

**Comment by saig0** [comment]
A new HTTP worker image is published on https://hub.docker.com/r/camunda/zeebe-http-worker.

Please verify if it is working now :)

**Comment by YounesTea** [comment]
I can't run the latest Docker image of this repo : 

```
2020-12-04 21:24:02.234  INFO 1 --- [           main] i.zeebe.http.ZeebeHttpWorkerApplication  : Starting ZeebeHttpWorkerApplication on d8e95588bc2b with PID 1 (/app/classes started by root in /)
2020-12-04 21:24:02.242 DEBUG 1 --- [           main] i.zeebe.http.ZeebeHttpWorkerApplication  : Running with Spring Boot v2.3.2.RELEASE, Spring v5.2.8.RELEASE
2020-12-04 21:24:02.243  INFO 1 --- [           main] i.zeebe.http.ZeebeHttpWorkerApplication  : No active profile set, falling back to default profiles: default
2020-12-04 21:24:04.347  INFO 1 --- [           main] i.z.s.c.c.p.ZeebeWorkerPostProcessor     : zeebeWorker: ClassInfo(bean=io.zeebe.http.ZeebeHttpWorkerApplication$$EnhancerBySpringCGLIB$$1a673fa1@55fee662, beanName=zeebeHttpWorkerApplication)
2020-12-04 21:24:05.053  INFO 1 --- [           main] i.z.s.c.c.p.ZeebeWorkerPostProcessor     : register job worker: ZeebeWorkerValue(type=http, name=http-worker, timeout=-1, maxJobsActive=-1, beanInfo=MethodInfo(classInfo=ClassInfo(bean=io.zeebe.http.ZeebeHttpWorkerApplication$$EnhancerBySpringCGLIB$$1a673fa1@55fee662, beanName=zeebeHttpWorkerApplication), method=public void io.zeebe.http.ZeebeHttpWorkerApplication.handleFooJob(io.zeebe.client.api.worker.JobClient,io.zeebe.client.api.response.ActivatedJob) throws java.io.IOException,java.lang.InterruptedException,java.util.concurrent.ExecutionException,java.util.concurrent.TimeoutException))
2020-12-04 21:24:05.122  INFO 1 --- [           main] i.zeebe.http.ZeebeHttpWorkerApplication  : Started ZeebeHttpWorkerApplication in 3.546 seconds (JVM running for 4.035)
2020-12-04 21:24:05.292  WARN 1 --- [ault-executor-1] io.zeebe.client.job.poller               : Failed to activated jobs for worker http-worker and job type http

io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:533) ~[grpc-api-1.30.2.jar:1.30.2]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:460) ~[grpc-stub-1.30.2.jar:1.30.2]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426) ~[grpc-core-1.30.2.jar:1.30.2]
	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66) ~[grpc-core-1.30.2.jar:1.30.2]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689) ~[grpc-core-1.30.2.jar:1.30.2]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577) ~[grpc-core-1.30.2.jar:1.30.2]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751) ~[grpc-core-1.30.2.jar:1.30.2]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740) ~[grpc-core-1.30.2.jar:1.30.2]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.30.2.jar:1.30.2]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[grpc-core-1.30.2.jar:1.30.2]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:26500
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779) ~[na:na]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

```

**Comment by saig0** [comment]
@YounesTea, the worker tries to connect to a Zeebe broker that runs on `127.0.0.1:26500`. Please check if this is the correct address of your Zeebe broker.
