### ISSUE TITLE
worker throws an error when API point returns the empty body

### ISSUE THREAD

**Issue by nervgh** [zeebe-io/zeebe-http-worker#54]
Hi everyone!

Zeebe and zeebe-http-worker both are very interesting ambitious solutions  :+1:  

I took one of our services which has a healthcheck API point `/api/healthcheck` which returns  the empty body to test zeebe-http-worker. And I had next error

```
java.lang.RuntimeException: Failed to deserialize response body from JSON: OK
    at io.zeebe.http.HttpJobHandler.bodyToObject(HttpJobHandler.java:189) ~[classes!/:0.22.0]
    at java.base/java.util.Optional.map(Optional.java:258) ~[na:na]
    at io.zeebe.http.HttpJobHandler.processResponse(HttpJobHandler.java:179) ~[classes!/:0.22.0]
    at io.zeebe.http.HttpJobHandler.handle(HttpJobHandler.java:77) ~[classes!/:0.22.0]
    at io.zeebe.http.ZeebeHttpWorkerApplication.handleFooJob(ZeebeHttpWorkerApplication.java:53) ~[classes!/:0.22.0]
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
    at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
    at io.zeebe.spring.client.bean.MethodInfo.invoke(MethodInfo.java:31) ~[spring-zeebe-0.22.0.jar!/:0.22.0]
    at io.zeebe.spring.client.config.processor.ZeebeWorkerPostProcessor.lambda$null$1(ZeebeWorkerPostProcessor.java:49) ~[spring-zeebe-0.22.0.jar!/:0.22.0]
    at io.zeebe.client.impl.worker.JobRunnableFactory.executeJob(JobRunnableFactory.java:44) ~[zeebe-client-java-0.22.0.jar!/:0.22.0]
    at io.zeebe.client.impl.worker.JobRunnableFactory.lambda$create$0(JobRunnableFactory.java:39) ~[zeebe-client-java-0.22.0.jar!/:0.22.0]
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
    at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]

```

Is it a bug or by design?

Thank you.

**Comment by saig0** [comment]
Hi @nervgh,

thank you for raising this up!

The worker should handle an empty response body. In this case, no variable `body` is created. If a body is returned then it assumes that the body is JSON. If it is not JSON then it fails.

It seems that the exception is raised because the body is not a JSON object. Instead, it is a plain text "OK".

Please check the response from the service and share it with this issue.

**Comment by nervgh** [comment]
@saig0 , thank you for your reply!

You was right :see_no_evil:  

1) When a server responds with `200` status code its response MUST have a body.
2) If a response does not have body at all then a server MUST respond with status `204` (No Content)

https://www.g33kzone.com/2017/05/http-status-codes-200-vs-202-vs-204.html

So we have changed 200 -> 204. zeebe-http-worker works fine :+1:
